### ISSUE TITLE
Support for tModLoader saves

### ISSUE THREAD

**Issue by IncubusRK** [nymda/WinTerrEdit#1] opened 2020-06-13 17:56 UTC
Steam version of tModLoader  0.11.7.5 uses Terraria 1.3.5.3 save format,
сan you add support for these save files?
WinTerrEdit crash when try to save edited file, couse hard coded offset unlockAllBeginOffser

**Comment by nymda** [comment] 2020-06-13 18:10
Caused by unused code, Should be fixed in this patch. Will be in the next release.
[WinTerrEdit.zip](https://github.com/nymda/WinTerrEdit/files/4775154/WinTerrEdit.zip)

**Closed as completed** 2020-06-14 23:16 UTC
